import { TRANSPORT_MODES } from '../utils/constants';

// Mock Cities
export const MOCK_CITIES = [
    { id: 1, name: 'Lagos', lat: 6.5244, lng: 3.3792, country: 'Nigeria' },
    { id: 2, name: 'Abuja', lat: 9.0765, lng: 7.3986, country: 'Nigeria' },
];

// Mock Stops
export const MOCK_STOPS = [
    {
        id: 1,
        name: 'Oshodi Terminal 1',
        latitude: 6.5569,
        longitude: 3.3484,
        city: 1,
        stop_type: TRANSPORT_MODES.BUS,
        is_popular: true,
    },
    {
        id: 2,
        name: 'Lekki Phase 1 Gate',
        latitude: 6.4468,
        longitude: 3.4731,
        city: 1,
        stop_type: TRANSPORT_MODES.BUS,
        is_popular: true,
    },
    {
        id: 3,
        name: 'Ojuelegba Underbridge',
        latitude: 6.5135,
        longitude: 3.3622,
        city: 1,
        stop_type: TRANSPORT_MODES.BUS,
        is_popular: true,
    },
    {
        id: 4,
        name: 'Ikeja Along',
        latitude: 6.5916,
        longitude: 3.3427,
        city: 1,
        stop_type: TRANSPORT_MODES.BUS,
        is_popular: true,
    },
    {
        id: 5,
        name: 'CMS Bus Stop',
        latitude: 6.4526,
        longitude: 3.3932,
        city: 1,
        stop_type: TRANSPORT_MODES.BUS,
        is_popular: true,
    },
    {
        id: 6,
        name: 'Eko Hotel Roundabout',
        latitude: 6.4277,
        longitude: 3.4300,
        city: 1,
        stop_type: TRANSPORT_MODES.KEKE,
        is_popular: false,
    },
];

// Mock Routes
export const MOCK_ROUTES = {
    search_results: [
        {
            id: 101,
            origin: 'Oshodi',
            destination: 'Lekki Phase 1',
            total_fare: 1200,
            total_duration_mins: 85,
            total_distance_km: 22.5,
            stops_count: 3,
            rating: 4.2,
            is_safest: true,
            is_cheapest: false,
            is_fastest: true,
            segments: [
                {
                    id: 1,
                    mode: TRANSPORT_MODES.WALK,
                    instruction: 'Walk to Oshodi Terminal 1',
                    duration_mins: 5,
                    distance_km: 0.3,
                    fare: 0,
                },
                {
                    id: 2,
                    mode: TRANSPORT_MODES.BUS,
                    instruction: 'Take BRT to CMS',
                    duration_mins: 45,
                    distance_km: 12.0,
                    fare: 800,
                    from_stop: 'Oshodi Terminal 1',
                    to_stop: 'CMS Bus Stop',
                },
                {
                    id: 3,
                    mode: TRANSPORT_MODES.BUS,
                    instruction: 'Take Danfo to Lekki Gate',
                    duration_mins: 30,
                    distance_km: 9.5,
                    fare: 400,
                    from_stop: 'CMS Bus Stop',
                    to_stop: 'Lekki Phase 1 Gate',
                },
                {
                    id: 4,
                    mode: TRANSPORT_MODES.WALK,
                    instruction: 'Walk to destination',
                    duration_mins: 5,
                    distance_km: 0.7,
                    fare: 0,
                },
            ],
        },
        {
            id: 102,
            origin: 'Oshodi',
            destination: 'Lekki Phase 1',
            total_fare: 800,
            total_duration_mins: 110,
            total_distance_km: 24.0,
            stops_count: 5,
            rating: 3.5,
            is_safest: false,
            is_cheapest: true,
            is_fastest: false,
            segments: [
                {
                    id: 1,
                    mode: TRANSPORT_MODES.WALK,
                    instruction: 'Walk to Oshodi Underbridge',
                    duration_mins: 10,
                    distance_km: 0.5,
                    fare: 0,
                },
                {
                    id: 2,
                    mode: TRANSPORT_MODES.BUS,
                    instruction: 'Take Danfo to Ojuelegba',
                    duration_mins: 25,
                    distance_km: 5.0,
                    fare: 200,
                },
                {
                    id: 3,
                    mode: TRANSPORT_MODES.BUS,
                    instruction: 'Take Danfo to CMS',
                    duration_mins: 35,
                    distance_km: 8.0,
                    fare: 300,
                },
                {
                    id: 4,
                    mode: TRANSPORT_MODES.BUS,
                    instruction: 'Take Danfo to Lekki',
                    duration_mins: 35,
                    distance_km: 10.0,
                    fare: 300,
                },
            ],
        },
        {
            id: 103,
            origin: 'Ikeja',
            destination: 'Yaba',
            total_fare: 500,
            total_duration_mins: 45,
            total_distance_km: 10.0,
            stops_count: 1,
            rating: 4.8,
            is_safest: true,
            is_cheapest: true,
            is_fastest: true,
            segments: [
                {
                    id: 1,
                    mode: TRANSPORT_MODES.KEKE,
                    instruction: 'Take Keke to Bus Stop',
                    duration_mins: 5,
                    distance_km: 1.0,
                    fare: 100,
                },
                {
                    id: 2,
                    mode: TRANSPORT_MODES.BUS,
                    instruction: 'Take BRT to Yaba',
                    duration_mins: 40,
                    distance_km: 9.0,
                    fare: 400,
                },
            ],
        },
    ],
};

export const MOCK_USER = {
    id: 1,
    name: 'Waka User',
    email: 'user@wakaway.com',
    avatar: 'https://i.pravatar.cc/150?u=wakaway',
};
