# Generated by Django 5.2.8 on 2025-11-18 12:44

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('bounds', core.models._PolygonField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'indexes': [models.Index(fields=['name', 'state'], name='core_city_name_b6d716_idx'), models.Index(fields=['is_active'], name='core_city_is_acti_f34fc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', core.models._PointField(default=dict)),
                ('destination', core.models._PointField(default=dict)),
                ('total_time_minutes', models.IntegerField()),
                ('total_distance_km', models.FloatField()),
                ('total_fare_ngn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('path', core.models._LineStringField(blank=True, null=True)),
                ('steps', models.JSONField(default=list)),
                ('view_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='TransportStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stop_type', models.CharField(choices=[('bus', 'Bus Stop'), ('keke', 'Keke Park'), ('okada', 'Okada Stand'), ('walk', 'Walking Point'), ('junction', 'Junction')], max_length=20)),
                ('location', core.models._PointField(default=dict)),
                ('address', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(blank=True, max_length=50)),
                ('transport_mode', models.CharField(choices=[('bus', 'Bus/Danfo'), ('keke', 'Keke/Tricycle'), ('okada', 'Okada/Motorbike'), ('walk', 'Walking')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('path', core.models._LineStringField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operating_hours_start', models.TimeField(blank=True, null=True)),
                ('operating_hours_end', models.TimeField(blank=True, null=True)),
                ('frequency_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.city')),
                ('destination_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='core.transportstop')),
                ('origin_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='core.transportstop')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('transport_mode', models.CharField(choices=[('bus', 'Bus/Danfo'), ('keke', 'Keke/Tricycle'), ('okada', 'Okada/Motorbike'), ('walk', 'Walking')], max_length=20)),
                ('instruction', models.TextField()),
                ('start_location', core.models._PointField(default=dict)),
                ('end_location', core.models._PointField(default=dict)),
                ('distance_km', models.FloatField()),
                ('duration_minutes', models.IntegerField()),
                ('fare_ngn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_steps', to='core.routesuggestion')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='core.transportroute')),
                ('intermediate_stops', models.ManyToManyField(blank=True, to='core.transportstop')),
            ],
            options={
                'ordering': ['suggestion', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('estimated_time_minutes', models.IntegerField(default=0)),
                ('distance_km', models.FloatField(default=0.0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.transportroute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.transportstop')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('report_count', models.IntegerField(default=0)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='core.transportroute')),
                ('destination_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fares_to', to='core.transportstop')),
                ('origin_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fares_from', to='core.transportstop')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoritePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_device_id', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('location', core.models._PointField(default=dict)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('fare_update', 'Fare Update'), ('route_disrupted', 'Route Disrupted'), ('new_route', 'New Route Available'), ('stop_moved', 'Stop Location Changed'), ('route_wrong', 'Route Information Incorrect'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', core.models._PointField(blank=True, null=True)),
                ('new_fare_ngn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_location', core.models._PointField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('user_device_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('fare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.fare')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.transportroute')),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.transportstop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_device_id', models.CharField(blank=True, max_length=200)),
                ('origin', core.models._PointField(default=dict)),
                ('destination', core.models._PointField(default=dict)),
                ('origin_name', models.CharField(blank=True, max_length=200)),
                ('destination_name', models.CharField(blank=True, max_length=200)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('route_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.routesuggestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='routesuggestion',
            index=models.Index(fields=['city', 'created_at'], name='core_routes_city_id_400115_idx'),
        ),
        migrations.AddIndex(
            model_name='routesuggestion',
            index=models.Index(fields=['view_count'], name='core_routes_view_co_e07929_idx'),
        ),
        migrations.AddIndex(
            model_name='transportstop',
            index=models.Index(fields=['stop_type', 'city'], name='core_transp_stop_ty_9633ad_idx'),
        ),
        migrations.AddIndex(
            model_name='transportstop',
            index=models.Index(fields=['is_verified'], name='core_transp_is_veri_c1cd22_idx'),
        ),
        migrations.AddIndex(
            model_name='transportroute',
            index=models.Index(fields=['transport_mode', 'city'], name='core_transp_transpo_49685d_idx'),
        ),
        migrations.AddIndex(
            model_name='transportroute',
            index=models.Index(fields=['is_active'], name='core_transp_is_acti_9a95c5_idx'),
        ),
        migrations.AddIndex(
            model_name='transportroute',
            index=models.Index(fields=['origin_stop', 'destination_stop'], name='core_transp_origin__ff545f_idx'),
        ),
        migrations.AddIndex(
            model_name='routestep',
            index=models.Index(fields=['suggestion', 'sequence'], name='core_routes_suggest_a95f60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestep',
            unique_together={('suggestion', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='routesegment',
            index=models.Index(fields=['route', 'sequence'], name='core_routes_route_i_08cdf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routesegment',
            unique_together={('route', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='fare',
            index=models.Index(fields=['route', 'is_verified'], name='core_fare_route_i_17a812_idx'),
        ),
        migrations.AddIndex(
            model_name='fare',
            index=models.Index(fields=['amount_ngn'], name='core_fare_amount__1e801d_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavoriteplace',
            index=models.Index(fields=['user'], name='core_userfa_user_id_86b018_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavoriteplace',
            index=models.Index(fields=['user_device_id'], name='core_userfa_user_de_3bc3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['report_type', 'status'], name='core_userre_report__4ee640_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['status', 'created_at'], name='core_userre_status_391491_idx'),
        ),
        migrations.AddIndex(
            model_name='userroutehistory',
            index=models.Index(fields=['user', '-searched_at'], name='core_userro_user_id_bed848_idx'),
        ),
        migrations.AddIndex(
            model_name='userroutehistory',
            index=models.Index(fields=['user_device_id', '-searched_at'], name='core_userro_user_de_570f24_idx'),
        ),
    ]
