// Dark map style for Google Maps matching WakaWay's #080D0B background
export const DARK_MAP_STYLE = [
  { elementType: 'geometry',                          stylers: [{ color: '#0f1610' }] },
  { elementType: 'labels.icon',                       stylers: [{ visibility: 'off' }] },
  { elementType: 'labels.text.fill',                  stylers: [{ color: '#5a7a64' }] },
  { elementType: 'labels.text.stroke',                stylers: [{ color: '#080d0b' }] },
  { featureType: 'administrative',      elementType: 'geometry',             stylers: [{ color: '#1a2e1e' }] },
  { featureType: 'administrative.country', elementType: 'labels.text.fill',  stylers: [{ color: '#9aa4a7' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#cdd3d4' }] },
  { featureType: 'poi',                 elementType: 'labels.text.fill',     stylers: [{ color: '#6b8f6b' }] },
  { featureType: 'poi.park',            elementType: 'geometry',             stylers: [{ color: '#0e1f11' }] },
  { featureType: 'poi.park',            elementType: 'labels.text.fill',     stylers: [{ color: '#3d7c47' }] },
  { featureType: 'poi.park',            elementType: 'labels.text.stroke',   stylers: [{ color: '#1b3a1f' }] },
  { featureType: 'road',                elementType: 'geometry',             stylers: [{ color: '#1f3324' }] },
  { featureType: 'road',                elementType: 'geometry.stroke',      stylers: [{ color: '#131e15' }] },
  { featureType: 'road',                elementType: 'labels.text.fill',     stylers: [{ color: '#8a9e8c' }] },
  { featureType: 'road.arterial',       elementType: 'geometry',             stylers: [{ color: '#253d2a' }] },
  { featureType: 'road.highway',        elementType: 'geometry',             stylers: [{ color: '#2d5233' }] },
  { featureType: 'road.highway',        elementType: 'geometry.stroke',      stylers: [{ color: '#1a3a1e' }] },
  { featureType: 'road.highway',        elementType: 'labels.text.fill',     stylers: [{ color: '#c5cfc6' }] },
  { featureType: 'transit',             elementType: 'geometry',             stylers: [{ color: '#132417' }] },
  { featureType: 'transit.station',     elementType: 'labels.text.fill',     stylers: [{ color: '#d59563' }] },
  { featureType: 'water',               elementType: 'geometry',             stylers: [{ color: '#040d08' }] },
  { featureType: 'water',               elementType: 'labels.text.fill',     stylers: [{ color: '#3d5a4d' }] },
  { featureType: 'water',               elementType: 'labels.text.stroke',   stylers: [{ color: '#17263c' }] },
];
